<script lang="ts">
	import * as api from '$lib/api/client';
	import type { CrashDiagnosis, DiagnosisPreview } from '$lib/api/types';

	let { serverName, crashEventId }: { serverName: string; crashEventId: number } = $props();

	let aiConfigured = $state(false);
	let diagnosis = $state<CrashDiagnosis | null>(null);
	let preview = $state<DiagnosisPreview | null>(null);
	let showPreview = $state(false);
	let loadingPreview = $state(false);
	let running = $state(false);
	let error = $state<string | null>(null);

	$effect(() => {
		aiConfigured = false;
		diagnosis = null;
		preview = null;
		showPreview = false;
		error = null;

		api
			.getAiStatus(fetch)
			.then((r) => {
				aiConfigured = r.data?.isConfigured ?? false;
			})
			.catch(() => {
				aiConfigured = false;
			});

		api
			.getCrashDiagnosis(fetch, serverName, crashEventId)
			.then((r) => {
				diagnosis = r.data;
			})
			.catch(() => {
				diagnosis = null;
			});
	});

	async function loadPreview() {
		showPreview = !showPreview;
		if (showPreview && !preview) {
			loadingPreview = true;
			try {
				const r = await api.previewCrashDiagnosis(fetch, serverName, crashEventId);
				if (r.error) {
					error = r.error;
				} else {
					preview = r.data;
				}
			} finally {
				loadingPreview = false;
			}
		}
	}

	async function diagnose() {
		running = true;
		error = null;
		try {
			const r = await api.runCrashDiagnosis(fetch, serverName, crashEventId);
			if (r.error) {
				error = r.error;
			} else {
				diagnosis = r.data;
			}
		} catch (e) {
			error = e instanceof Error ? e.message : 'Diagnosis failed.';
		} finally {
			running = false;
		}
	}
</script>

{#if aiConfigured}
	<section class="diagnosis">
		{#if diagnosis?.status === 'complete'}
			<h4>AI summary</h4>
			<p class="disclaimer">
				Machine-generated. Verify against the crash log before acting on it.
			</p>
			{#if diagnosis.summary}<p>{diagnosis.summary}</p>{/if}
			{#if diagnosis.likelyCause}
				<p><strong>Likely cause:</strong> {diagnosis.likelyCause}</p>
			{/if}
			{#if diagnosis.suggestedActions.length}
				<ul>
					{#each diagnosis.suggestedActions as action}<li>{action}</li>{/each}
				</ul>
			{/if}
			<p class="meta">Generated by {diagnosis.model} on {new Date(diagnosis.createdAt).toLocaleString()}.</p>
		{:else if diagnosis?.status === 'failed'}
			<p class="error">Diagnosis failed: {diagnosis.error}</p>
		{:else if diagnosis?.status === 'pending'}
			<p class="meta">Diagnosis in progress…</p>
		{:else}
			<button onclick={diagnose} disabled={running}>
				{running ? 'Diagnosing…' : 'Diagnose this crash'}
			</button>
		{/if}

		{#if error}<p class="error">{error}</p>{/if}

		<button class="link" onclick={loadPreview}>
			{showPreview ? 'Hide' : 'Show'} what will be sent
		</button>
		{#if showPreview}
			{#if loadingPreview}
				<p class="meta">Loading preview…</p>
			{:else if preview}
				<p class="meta">
					{preview.approxCharacters} characters &middot; redacted: {preview.rulesApplied.join(', ') ||
						'nothing'}
				</p>
				<pre>{preview.redactedInput}</pre>
			{/if}
		{/if}
	</section>
{/if}

<style>
	.diagnosis {
		display: flex;
		flex-direction: column;
		gap: 0.6rem;
		padding: 0.75rem 1rem;
		border: 1px solid var(--border-color, #30363d);
		border-radius: 6px;
	}
	.diagnosis h4 {
		margin: 0;
	}
	.disclaimer {
		font-size: 0.8rem;
		font-style: italic;
		opacity: 0.75;
		margin: 0;
	}
	pre {
		overflow-x: auto;
		max-height: 20rem;
		white-space: pre-wrap;
		word-break: break-word;
		font-size: 0.8rem;
		background: var(--code-bg, #0d1117);
		padding: 0.5rem;
		border-radius: 4px;
	}
	.meta {
		font-size: 0.85rem;
		opacity: 0.7;
		margin: 0;
	}
	.error {
		color: var(--color-error, #ef4444);
		margin: 0;
	}
	button.link {
		align-self: flex-start;
		background: none;
		border: none;
		padding: 0;
		color: var(--accent-color, #58a6ff);
		cursor: pointer;
		text-decoration: underline;
		font-size: 0.85rem;
	}
</style>
